dist: xenial
language: java
jdk:
  - openjdk11
script: psql -c "SELECT version();" && gradle clean test


before_install:
  - chmod +x gradlew
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11

before_script:
  - psql -c 'create database demowebpostgre;' -U postgres

services:
  - postgresql

env:
  global:
  - PGUSER=postgres
  - PGPORT=5432


